#!/bin/bash
# Copyright 2015-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later

# look up ips for url and then find them in ipsets
[ $# -eq 0 ] && echo "Enter a url to test" && exit -1

for ip in $(dig +short "$1")  $(dig AAAA +short "$1")
do
  echo "--------[ $ip ]---------------"
  ipset-find $ip | grep 'IS'
done
