#!/bin/sh
# Copyright 2025-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later

exec tail -n +3 $0
# This file provides an easy way to add custom commands for the grub menu.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
color_normal=blue/black
menu_color_normal=black/black
menu_color_highlight=magenta/black
