#!/bin/bash
# Copyright 2009-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later
#
#mysubnet="192.168.7.0/24"
#mysubnet="192.168.67.0/24"
#mysubnet="192.168.66.0/24"
#mysubnet="192.168.1.0/24"
#mysubnet="192.168.64.0/22"

user="joe"
outfile="/home/${user}/nmap_report"

ABnet="192.168"
#ABnet="10.0"

Cnet="${1:-62}"
MASKbits="${2:-24}"

mysubnet="${ABnet}.${Cnet}.0/${MASKbits}"
rm -f "${outfile}"
echo "Scanning subnet [ ${mysubnet} ]..."
nmap -A -T5 -p22 -v3 "${mysubnet}" > "${outfile}"

echo && echo "Found info for:"
cat "${outfile}" | grep -v 'host down' | grep '(' | grep 'report for'
