#!/bin/bash
# Copyright 2014-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later

# source this in your .bashrc file, where it says "Put your fun stuff here."

#-----[ my aliases ]--------------------------------------------------------------------
alias ll='ls -l --color=tty' 2>/dev/null
alias la='ls -al --color=tty' 2>/dev/null
alias lt='ls -alt --color=tty' 2>/dev/null
alias lr='ls -altr --color=tty' 2>/dev/null
alias lsr='ls -Slr --color=tty' 2>/dev/null
alias lz='ls -alZ --color=tty' 2>/dev/null

alias grep='grep --binary-files=text --color=auto'

# strip blank lines and comments (clean view); note: \s is PCRE for zero+ whitespace
#alias cv='grep -Ev --color=auto "(^\s*$|^\s*#)" 2>/dev/null'
# ERE equivalent, where script_header_joetoo has defined W0="[[:space:]]*" (joetoo for zero+ whitespace)
alias     cv='grep -Ev --color=auto "(^${W0}$|^${W0}#)" 2>/dev/null'

alias dusort='du -bchx -d2 | sort -h'

alias     ce='checknotroot && check_everybody.sh'

alias     es='emerge --sync joetoo && eix -uc --in-overlay joetoo'
alias     en='eix -#'  # eix names

alias   tmux='LC_CTYPE=en_US.utf8 tmux'  # force tmux   to utf-8
alias screen='screen -U'                 # force screen to utf-8
alias   nano='LC_ALL=en_US.UTF8 nano --tabsize=2'
alias     bt='LC_ALL=en_US.UTF8 btop'

alias    dig='dig +search'

# remove pre-existing alias (which gcsm used to be) so we can use this function
unalias gcsm 2>/dev/null
gcsm() # (BASH) submit signed commit (follow with gpom to push)
{   local _gcsm_msg="${1:-}"
    echo 'test' > ~/cachetest  #.............................# create a dummy file to sign
    gpg --clearsign ~/cachetest > /dev/null 2>&1 || true  #..# sign file w pinentry, cache the key, ignore pcscd error msg
    [ -f ~/cachetest.asc ] || return 1   #...................# verify the file signature (.asc) was created
    rm ~/cachetest.asc  #....................................# remove the signature to reset
    git commit -s -S -m "${_gcsm_msg}"  #....................# signoff and sign the commit
}
# @usage gcsm <message>
# @note author converted alias gcsm to a function for clarity, but this is still built
# @append to treat gpg failure as a warning rather than a blocker
# @note for git commit options --
# @cont  -s | --signoff = add Signed-off-by line IAW GLEP-76 (DCO)
# @cont  -S | --gpg-sign [<key-id>] = sign w gnupg signing key (or --no-gpg-sign; overrides default)
# @note reference: https://www.kernel.org/pub/software/scm/git/docs/git-commit.html
# @note if a repo's ./.git/config or the users /home/<user>/.gitconfig contains "gpgsign = true" in a [commit]
# @cont block, and "signingkey = <gpg-key-id>" in a [user] block, then --gpg-sign will default
# @cont to that and --no-gpg-sign will turn it off

pcsm() # (BASH) submit signed commit (follow with gpom to push)
{   local _gcsm_msg="${1:-}"
    echo 'test' > ~/cachetest  #.............................# create a dummy file to sign
    gpg --clearsign ~/cachetest > /dev/null 2>&1 || true  #..# sign file w pinentry, cache the key, ignore pcscd error msg
    [ -f ~/cachetest.asc ] || return 1   #...................# verify the file signature (.asc) was created
    rm ~/cachetest.asc  #....................................# remove the signature to reset
    pkgdev commit --scan --signoff --gpg-sign -m "${_gcsm_msg}"  # signoff and sign the commit
}
# @usage pcsm <message>
# @note note for pkgdev commit options --
# @rule pcsm is prefered for eclass maintenance due tobetter metadata manifest mgmt via pkgdev commit
# @cont  -s | --scan for QA
# @warn  (*** caveat: for pkgdev commit, -s is NOT --signoff ***)
# @cont  --signoff = add Signed-off-by line IAW GLEP-76 (DCO)
# @cont  --gpg-sign (or --no-gpg-sign) passes --gpg-sign to git --commit
# @cont  (there is no capital -S for pkgdev)
# @note reference: https://pkgcore.github.io/pkgdev/man/pkgdev.html#id4
# @note if a repo's ./.git/config or the users /home/<user>/.gitconfig contains "gpgsign = true" in a [commit]
# @cont block, and "signingkey = <gpg-key-id>" in a [user] block, then --gpg-sign will default
# @cont to that and --no-gpg-sign will turn it off

alias   gpom='git push origin master'

alias     qm='qemu-image-mount'
alias     ql='qemu-image-launch'

alias     ow='xdotool_open_windows'
alias     cw='xdotool_close_windows'
alias     mw='xdotool_sizemove_this_window'

alias     tl='tail -n50'

alias     mb='mount /boot'

alias kmerge='FEATURES="-getbinpkg -buildpkg -distcc" emerge -av --verbose-conflicts'
alias icmerge='FEATURES="-collision-detect -protect-owned" emerge -1 --verbose-conflicts'
alias nobinmerge='MAKEOPTS="-j2 -l2" FEATURES="-getbinpkg -buildpkg -userpriv -distcc" emerge -1 --verbose-conflicts'
alias j1merge='MAKEOPTS="-j1" FEATURES="-getbinpkg -buildpkg -userpriv -distcc" emerge -1 --verbose-conflicts'
alias nodistmerge='MAKEOPTS="-j2 -l2" FEATURES="-userpriv -distcc" emerge -1 --verbose-conflicts'

#-----[ my PATH ]-----------------------------------------------------------------------
#export PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/bin:/sbin:/usr/sbin:/root/bin:/usr/local/sbin:/usr/local/bin:${PATH}:/opt/bin:/home/joe/script
export PATH=/usr/lib/distcc/bin:${PATH}:/home/joe/script

#/usr/sbin:/usr/bin:/sbin:/bin:

#alias dist_path='export PATH=/usr/lib/distcc/bin:/root/bin:/usr/local/sbin:/usr/local/bin:${PATH}:/opt/bin:/home/joe/script'
alias dist_path='export PATH=/usr/lib/distcc/bin:${PATH}:/home/joe/script'

alias nodist_path='source /usr/sbin/setnodistpath'

which()         # return full path of executable "$1"
{ (alias; declare -f) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@ ; }
export -f which

mequery_b()     # identify the package that installed file $1
{ (alias; declare -f) | grep -l -r -e $(echo "bin/"$(basename $(which ${1?} ))) /var/db/pkg/ --include=CONTENTS | awk -F'/' '{print $5"/"$6}' ; }


#-----[ PORTDIR, PKGDIR, DISTDIR ]-----------------------------------------------------
#export        PORTDIR=$(source /etc/portage/make.conf 2>/dev/null; echo "${PORTDIR:-/var/db/repos/gentoo}")
#export         PKGDIR=$(source /etc/portage/make.conf 2>/dev/null; echo "${PKGDIR:-/var/cache/binpkgs}")
#export        DISTDIR=$(source /etc/portage/make.conf 2>/dev/null; echo "${DISTDIR:-/var/cache/distfiles}")
#export PORTAGE_TMPDIR=$(source /etc/portage/make.conf 2>/dev/null; echo "${PORTAGE_TMPDIR:-/var/tmp}")
#export PORTAGE_LOGDIR=$(source /etc/portage/make.conf 2>/dev/null; echo "${PORTAGE_LOGDIR:-/var/log/portage}")
# use new approach, below

#-----[ portage environment cache ]--------------------------------------------------
_load_portage_env() {
    # source the file natively once so shell handles ROOT and path nesting for all variables
    if [ -f /etc/portage/make.conf ]; then
        . /etc/portage/make.conf 2>/dev/null
    fi

    # export variables globally, applying Gentoo's standard fallback defaults
    export PORTDIR="${PORTDIR:-/var/db/repos/gentoo}"
    export PKGDIR="${PKGDIR:-/var/cache/binpkgs}"
    export DISTDIR="${DISTDIR:-/var/cache/distfiles}"
    export PORTAGE_TMPDIR="${PORTAGE_TMPDIR:-/var/tmp}"
    export PORTAGE_LOGDIR="${PORTAGE_LOGDIR:-/var/log/portage}"
}
_load_portage_env
unset -f _load_portage_env  # clean up the function namespace immediately

export DISTCC_DIR="${PORTAGE_TMPDIR%/}/portage/.distcc/"

alias distmon='DISTCC_DIR="${DISTCC_DIR}" distccmon-text 2'
alias distgui='DISTCC_DIR="${DISTCC_DIR}" distccmon-gui'
