#!/bin/bash
# Copyright 2025-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later
#

TARGETS=(
    'aarch64-unknown-linux-gnu'
    'armv6j-unknown-linux-gnueabihf'
    'armv7a-unknown-linux-gnueabihf'
)
yes | for TARGET in ${TARGETS[@]}; do
    crossdev -C -t ${TARGET};
done && \
\
for TARGET in ${TARGETS[@]}; do
    crossdev -S -t ${TARGET};
done
