#!/bin/bash
# Copyright 2025-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later
#
# get-drivers_2 - updated version of get-drivers using associative array to also collect "what is it for?"

source /usr/sbin/script_header_joetoo

PN=${0##*/}

if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD="0.0.1"; fi

declare -A driver_map   #......# each stored value is an accumulated list of devices, keyed to driver used
declare -a unique_drivers=()   # an indexed array of driver names

# set up a pattern match for pci address (e.g. 00:1f.4 --> [optional4-hex:]2-hex:2-hex.hex space)
pci_addr_pattern='^([[:xdigit:]]{4}:)?[[:xdigit:]]{2}:[[:xdigit:]]{2}\.[0-7][[:space:]]'
lspci_driver_pattern="^${W0}Kernel${W1}driver${W1}in${W1}use:${W1}(.+)"
lspci_modules_pattern="^${W0}Kernel${W1}modules:${W1}(.+)$"

# similarly set up a pattern match for lshw node entries (e.g.   *-display  --> zero+ whitespace *-<name> )
lshw_node_pattern="^${W0}\*-"
lshw_product_pattern="^${W0}\product:"
lshw_desc_pattern="^${W0}\description:"
lshw_config_pattern="^${W0}\configuration:"

# define lspci and lshw commands
lspci_cmd=(lspci -D -n -n -k)   # -Dnnk - D: show domain number; nn: show both text and numeric; k: show kernel drivers
lshw_cmd=(lshw -numeric)        # (maybe change this to -json and use jq??)

# define offset for info displayed right of progress bar
offset=60   # determined empirically  Working: [##############################] 100% (63/63) => 55

# enable silent output default
target_output_path="/dev/null"
# verbose option uses stdout
[[ $DEBUG || $verbosity -ge 7 ]] && target_output_path="/dev/stdout"

separator "$(hostname)" "${PN}-${BUILD}"

j_msg "-${debug}" -p "DEBUG: $(status_color $DEBUG)$(TrueFalse $DEBUG)${Boff}"
j_msg "-${debug}" -p "verbosity: $verbosity"
j_msg "-${debug}" -p "target_output_path: $target_output_path"

# ingest from lspci by examining one block at a time
current_device=""

# iterate through lines of lspci -k
j_msg "-${notice}" -p "Finding drivers identified by lspci; please wait ..."
# prepare to use progress bar
lines=$("${lspci_cmd[@]}" | wc -l)
line_num=0
HCU   # hide cursor while using progress bar
while IFS= read -r line; do
    # update the progress bar
    progress_inline "$((line_num++))" "$lines"
    # prep to show some extra info to the right (save pos; return left; adv to offset)
    SCP; printf '\r'; CUF $offset
    # print a sample of what line is being considered
    printf '%s' "${line:0:10}"
    # clear the rest of the line and return to saved pos
    EL; RCP
    # remove trailing carriage returns
    line=$(echo "$line" | tr -d '\r')
    j_msg "-${debug}" -p "line: [$line]"
    # if the line starts with a PCI address (e.g., 00:1f.4), grab the device description
    # do not quote the target pattern, or bash will treat it as literal text rather than ERE
    if [[ "$line" =~ ${pci_addr_pattern} ]]; then
    # (re)initialize driver-collector
        driver=""
        # strip the leading PCI address prefix to isolate the device description
        current_device=$(echo "$line" | sed -E "s/${pci_addr_pattern} //")
        j_msg "-${debug}" -p "current_device: [$current_device]"
    # if the line shows driver, map to description; use ^^ force caps to be case-insensitive
    elif [[ "$line" =~ ${lspci_driver_pattern} ]]; then
        # note: xargs w/o a cmd defaults to echo, which trims whitespace
        driver=$(echo "$line" | awk -F': ' '{print $2}' | xargs)
        j_msg "-${debug}" -p "driver: [$driver]"
        # check what has been found - if no driver, nothing to do
        if [ -n "$driver" ]; then
            # there should always be a device description - so handle error if not
            if [ -n "$current_device" ]; then
                # append if the driver already has some mapped hardware, otherwise assign its first
                if [ -n "${driver_map[$driver]}" ]; then
                    driver_map[$driver]="${driver_map[$driver]} / $current_device"
                else
                    driver_map[$driver]="$current_device"
                    unique_drivers+=("$driver")
                fi
            else
                die "current_device [$current_device] should not be empty"
            fi
        fi
    else
        j_msg "-${debug}" -p "line matched neither pci_addr_pattern nor lspci_driver_pattern"
        j_msg "-${debug}" -p "pci_addr_pattern: [$pci_addr_pattern]"
        j_msg "-${debug}" -p "lspci_driver_pattern: [$lspci_driver_pattern]"
    fi
done < <("${lspci_cmd[@]}" 2>&1)
result=$?
progress_inline "$lines" "$lines"   # finish progress bar at 100%
# go up one line; clean up right of progress bar
CUU 1; printf '\r'; CUF $offset; EL
printf '\n'
j_msg "-${notice}" -p -n "Done processing lspci; result:"
handle_result $result "ingested [${#driver_map[@]}]" "" "$notice"

# iterate through lines of lshw
j_msg "-${notice}" -p -n "Finding drivers identified by lshw; please wait ..."
# prepare to use progress bar
lines=$("${lshw_cmd[@]}" | wc -l)
line_num=0
HCU   # hide cursor while using progress bar
while IFS= read -r line; do
    # update the progress bar
    progress_inline "$((line_num++))" "$lines"
    # prep to show some extra info to the right (save pos; return left; adv to offset)
    SCP; printf '\r'; CUF $offset
    # print a sample of what line is being considered
    printf '%s' "${line:0:10}"
    # clear the rest of the line and return to saved pos
    EL; RCP
    # remove trailing carriage returns
    line=$(echo "$line" | tr -d '\r')
    j_msg "-${debug}" -p "line: [$line]"
    # if the line starts with a node name (e.g., *-display), reset collectors
    # do not quote the target pattern, or bash will treat it as literal text rather than ERE
    if [[ "$line" =~ ${lshw_node_pattern} ]]; then
    # (re)initialize collectors - both because device description does not come from this line like w lspci
        driver="" ; current_device=""
        current_lshw_product=""; current_lshw_desc=""
    # collect, to append product info to device description
    elif [[ "$line" =~ ${lshw_product_pattern} ]]; then
        # note: xargs w/o a cmd defaults to echo, which trims whitespace
        current_lshw_product=$(echo "$line" | awk -F': ' '{print $2}' | xargs)
        current_device="${current_device}${current_lshw_product}"
        j_msg "-${debug}" -p "current_lshw_product: [$current_lshw_product]"
        j_msg "-${debug}" -p "current_device: [$current_device]"
    # collect to prepend description: to device description
    elif [[ "$line" =~ ${lshw_desc_pattern} ]]; then
        # note: xargs w/o a cmd defaults to echo, which trims whitespace
        current_lshw_desc=$(echo "$line" | awk -F': ' '{print $2}' | xargs)
        current_device="${current_lshw_desc}: ${current_device}"
        j_msg "-${debug}" -p "current_lshw_desc: [$current_lshw_desc]"
        j_msg "-${debug}" -p "current_device: [$current_device]"
    # if the line shows driver, extract and map to description; use ^^ force caps to be case-insensitive
    elif [[ "$line" =~ ${lshw_config_pattern} ]]; then
        # use parameter expansion extract the driver name from driver=<name> assignment
        tmp="${line##*driver=}"   # strip from prefix all thru and including driver=
        driver="${tmp%%\ *}"      # strip from suffix all including space after <name>
        j_msg "-${debug}" -p "driver: [$driver]"
        # check what has been found - if no driver, nothing to do
        if [ -n "$driver" ]; then
            # there should always be a device description - so handle error if not
            if [ -n "$current_device" ]; then
                # append if the driver already has some mapped hardware, otherwise assign its first
                if [ -n "${driver_map[$driver]}" ]; then
                    driver_map[$driver]="${driver_map[$driver]} / $current_device"
                else
                    driver_map[$driver]="$current_device"
                    unique_drivers+=("$driver")
                fi
            else
                die "current_device [$current_device] should not be empty"
            fi
        fi
    else
        msg="line matched none of lshw_node_pattern lshw_product_pattern lshw_desc_pattern lshw_config_pattern"
        j_msg "-${debug}" -p "$msg"
        j_msg "-${debug}" -p "lshw_node_pattern: [$lshw_node_pattern]"
        j_msg "-${debug}" -p "lshw_product_pattern: [$lshw_product_pattern]"
        j_msg "-${debug}" -p "lshw_desc_pattern: [$lshw_desc_pattern]"
        j_msg "-${debug}" -p "lshw_config_pattern: [$lshw_config_pattern]"
    fi
done < <("${lshw_cmd[@]}" 2>&1)
result=$?
progress_inline "$lines" "$lines"   # finish progress bar at 100%
# go up one line; clean up right of progress bar
CUU 1; printf '\r'; CUF $offset; EL
printf '\n'
j_msg "-${notice}" -p -n "Done processing lspci; result:"
handle_result $result "ingested [${#driver_map[@]}]" "" "$notice"

# sort the keys of the driver_map into the indexed array of sorted driver names
j_msg "-${notice}" -p -n "Sorting unique drivers to new array ..."
readarray -t sorted_drivers < <(printf '%s\n' "${!driver_map[@]}" | sort -u)
handle_result $? "total drivers [${#sorted_drivers[@]}]" "" "$notice"

# display accumulated data in sorted-driver order
printf '\n'
longest=$(get_longest "${!sorted_drivers[@]}")
j_msg "-${debug}" -p "longest: [$longest]"
col_width=$(( longest + 2 ))
for i in "${!sorted_drivers[@]}"; do
    driver="${sorted_drivers[i]}"
    hardware="${driver_map[$driver]}"
    # print in fixed-width columns
    printf "\t%02s: %-${col_width}s %s: %s\n" "$i" "$driver" "$(repeat '.' $(( col_width - ${#driver})) )" "$hardware"
done
printf '\n'

