#!/bin/bash
# Copyright 2025-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later

source /usr/sbin/script_header_joetoo

PN=${0##*/}

if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD="0.0.1"; fi

declare -a driverlist=()
declare -a combinedlist=()

# enable silent output default
target_output_path="/dev/null"
# verbose option uses stdout
[[ $DEBUG || $verbosity -ge 7 ]] && target_output_path="/dev/stdout"

separator "$(hostname)" "${PN}-${BUILD}"

j_msg "-${debug}" -p "DEBUG: $(status_color $DEBUG)$(TrueFalse $DEBUG)${Boff}"
j_msg "-${debug}" -p "verbosity: $verbosity"
j_msg "-${debug}" -p "target_output_path: $target_output_path"

j_msg "-${notice}" -p -n "Finding drivers identified by lspci ..."
# use tr -d '\r' to remove trailing \r; sort -u to dedupe; awk to pick value(s) following the :
readarray -t driverlist < <(
    lspci -k 2>&1 | grep -i kernel | tr -d '\r' | sort -u | awk -F': ' '{ print $2 }'
) &>"$target_output_path"
handle_result $? "ingested [${#driverlist[@]}]" "" "$notice"

j_msg "-${notice}" -p -n "Finding drivers identified by lshw ..."
# use -O (origin) to append to array; tr -d '\r' to remove trailing \r
readarray -O ${#driverlist[@]} -t driverlist < <(
    lshw 2>&1 | grep -i driver | awk -F'=' '{ print $2 }' | sed 's/latency//' | tr -d '\r' | sort -u
) &>"$target_output_path"
handle_result $? "total ingested [${#driverlist[@]}]" "" "$notice"

j_msg "-${notice}" -p -n "Sorting and deduplicating ..."
# use sed to trim leading and trailing whitespace; sort -u to deduplicate
readarray -t combinedlist < <( printf '%s\n' "${driverlist[@]}" | sed "s/^${W0}//" | sed "s/${W0}$//" | sort -u )
handle_result $? "total ingested [${#driverlist[@]}]" "" "$notice"

printf '\n'
# iterate over the index of the array with ${!var[@]}
for i in "${!combinedlist[@]}"; do
    printf '\t%s: %s\n' "$i" "${combinedlist[i]}"
done
printf '\n'
