#!/bin/bash
# Copyright 2014-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later

# clean out old kernel residue
#
source /usr/sbin/script_header_joetoo

PN=${0##*/}   # basename

if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD=0.0.1; fi

get_yn_reply()
{
  unset reply
  yn_prompt  "delete $1 residual for of kernel $2 [y/n]? "
  case "$answer" in
    [yY]*) return 0 ;;
    [nN]*) return 1 ;;
    *) die "invalid answer from yn_prompt" ;;
  esac
  return 0
}

clean_residue()
{
  [ $# -eq 0 ] && die "selector \$1 empty [$1]"
  [ $# -eq 1 ] || die "invalid args in clean_residue [$*]"
  selector="$1"
  j_msg "-${notice}" -p "sources found:"
  ls -al /usr/src/linux-*${selector}*
  if get_yn_reply "sources" "${selector}"; then
    j_msg "-${notice}" -p "deleting sources residual for kernel ${selector}"
    rm -rfv /usr/src/linux-*${selector}*
  else
    j_msg "-${notice}" -p "Aborting at user direction"
    exit 1
  fi

  j_msg "-${notice}" -p "modules found:"
  ls -al /lib/modules/*${selector}*
  if get_yn_reply "modules" "${selector}"; then
    j_msg "-${notice}" -p "deleting modules residual for kernel ${selector}"
    rm -rfv /lib/modules/*${selector}*
  else
    j_msg "-${notice}" -p "Aborting at user direction"
    exit 1
  fi

  j_msg "-${notice}" -p "boot images found:"
  ls -al /boot/*${selector}*
  if get_yn_reply "images" "${selector}"; then
    j_msg "-${notice}" -p "deleting images residual for kernel ${selector}"
    rm -rfv /boot/*${selector}*
  else
    j_msg "-${notice}" -p "Aborting at user direction"
    exit 1
  fi
}

#---[ main script ]---------------------------
checkroot
separator "$(hostname)" "${PN}-${BUILD}"

if [[ -z "$1" ]]
then
  j_msg "-${notice}" -p "listing kernel versions found..."
  j_msg "-${notice}" -p "sources:" && ls -al /usr/src/
  j_msg "-${notice}" -p "modules:" && ls -al /lib/modules/
  j_msg "-${notice}" -p "images:"  && ls -al /boot/
else
  j_msg "-${notice}" -p "cleaning residue of kernels identified by filter [$1]"
  clean_residue "$1"
fi
