#!/bin/bash
# Copyright 2025-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later
source /usr/sbin/script_header_joetoo

PN=${0##*/}   #  like =$(basename $0) but w/o subshell and function call

if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD="0.0.1"; fi

[ -z "$verbosity" ] && verbosity="${notice}"  # assign default if null; allow calling program to dictate

#-----[ main script ]------------------------------------------------

for iface in $(netstat -iaw | grep -v Kernel | grep -v Iface | awk '{print $1}')
do
  readarray -t altnames < <(ip link show dev ${iface} | grep altname | awk '{print $2}')
  if [ ${#altnames[@]} -gt 0 ]
  then
    j_msg "-${notice}" -p -n "  ${iface}: "
    for x in "${altnames[@]}"
    do
      j_msg "-${notice}" -mp -n "$x "
    done
    j_msg "-${notice}" -mp ""  # newline
  fi
done
