#!/bin/bash
# Copyright 2009-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later

# /usr/sbin/loggit
#
# Modified from John Brendler's Rev. 20 July 2007

[[ $# -gt 2 ]] && printf "invalid loggit arguments\n" && exit 1;
PROGRAM="${1:-Unspecified}"
EXIT_STATUS="${2:-0}"
case "$EXIT_STATUS" in
    0) PRIORITY="notice" && MESSAGE="succeeded" ;;
    *) PRIORITY="err" && MESSAGE="failed with exit status [${EXIT_STATUS}]" ;;
esac;
/usr/bin/logger -p "cron.$PRIORITY" "${PROGRAM} ${MESSAGE}"
