#!/bin/bash
# Copyright 2025-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later
#
source /usr/sbin/script_header_joetoo
checkroot

nextcloud_config_dir="/var/www/localhost/htdocs/myCloud/config/"
for x in $(find "${nextcloud_config_dir}" -iname '*.php' | grep -v sample); do
    echo;
    echo "$x" ;
    echo $(repeat '-' ${#x});
    sudo cat "$x";
done
