#!/bin/bash
# Copyright 2025-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later

cd
umount -R /mnt/gentoo
echo "mount | grep gentoo..."
mount | grep gentoo

root_vg=$(lvs | grep root | awk '{print $2}')
vgchange -an "${root_vg}"
echo

for x in /dev/mapper/ed*
do
  cryptsetup luksClose "$x"
done

echo
echo "/dev/mapper/ed*..."
ls -al /dev/mapper/ed*
