#!/bin/bash
# Copyright 2025-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later

# resetMySqlRootPassword - like it says; pick a password, then save, and run reset command
#

# /etc/init.d/mysql stop
# create file /home/joe/mysql_init with this content -->///
# "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('<password>');"
#as root, issue the command:
# mysqld_safe --init-file=/home/joe/mysql_init &
#you should now be able to start mysql and login
# /etc/init.d/mysql start
# mysql -u root -h localhost -p  (supply password chosen above in response to prompt)

#see also -- http://dev.mysql.com/doc/refman/5.7/en/resetting-permissions.html


source /usr/sbin/script_header_joetoo


PN=${0##*/}   #  like =$(basename $0) but w/o subshell and function call

if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD="0.0.1"; fi

[ -z "$verbosity" ] && verbosity=${notice}  # assign default if null; allow calling program to dictate

#-----[ variables ]---------------------------------------------------------
user="joe"

#-----[ main script ]-------------------------------------------------------
checkroot

# stop the mysql server:
j_msg "-${notice}" -p -n "Stopping mysql server"
/etc/init.d/mysql stop &>/dev/null
right_status $?

result=""
# get a new password and store it as part of mysql_init file
if pass=$(ask_pass " $bin_key ${BWon}Enter a new root password for mysql:${Boff} "); then
    echo "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${pass}');" > "/home/${user}/mysql_init"
    result=$?
else
    die "failed to set new password"
fi
handle_result $result "ok [${#pass}] char pwd" "" "$notice"

# now reset the password
j_msg "-${notice}" -p -n "Running mysqld_safe in the background, to reset password"
mysqld_safe --init-file=/home/joe/mysql_init &>/dev/null & pid=$!
handle_result $? "ran as pid [$pid]" "error" || die "failed to reset password"

j_msg "-${notice}" -p -n "Restarting mysql server"
/etc/init.d/mysql start &>/dev/null
right_status $?
