#!/usr/bin/python3
# Copyright 2015-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later
#
# python_canary - use this script to test validate_scripts by changing comment in/out below

import portage
mtimedb = portage.mtimedb

#print("----[ resume ]----")    # should pass validate_scripts
print("----[ resume ]----"     # should fail validate_scripts [ missing ) ]
print(portage.mtimedb.get("resume", {}).get("mergelist"))
print("----[ resume_backup ]----")
print(portage.mtimedb.get("resume_backup", {}).get("mergelist"))
