#!/bin/bash
# Copyright 2025-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later
10.0.4-building
# PKG_PVR - dummy placeholder for testing ckinitramfs, which uses ${MAKE_DIR%/}/PKG_PVR populated by ebuild
#./ckinitramfs:  # PKG_PVR is populated by make_sources.sh in /usr/src/mkinitramfs
#./ckinitramfs:  BUILD="$(cat ${MAKE_DIR%/}/PKG_PVR)"
