#!/bin/bash
# Copyright 2014-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later

source /usr/sbin/script_header_joetoo
for x in init validated_functions_header testing_functions_header
do
    separator "$x" "1. checking for d_ lines missing verbosity level in"
    ./check_d_message_levels ../$x
    separator "$x" "2. checking for missing quotation marks in"
    ./find_missing_quotation_mark ../$x
    echo
done
