#!/bin/bash
# Copyright 2014-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later

# works on the cmdline; not sure why not in script
inputfile=$1
[ $# -eq 0 ] || [ ! -f $inputfile ] && exit
n=1; while read line; do \
quote_count=$(echo $line | tr -d -c '"\n' | awk '{ print length; }'); \
[ $(($quote_count % 2)) -eq 1 ] && echo "$quote_count  <----- *** ---- *** ----" && \
echo "$n: $line"; \
let n++; \
#done < ./ash_testing/testing_functions_header
done < ${inputfile}
