#!/bin/bash
# Copyright 2014-2026 Joseph Brendler
# SPDX-License-Identifier: GPL-3.0-or-later

source /usr/sbin/script_header_joetoo
for x in init validated_functions_header testing_functions_header
do
    separator "$x" "listing functions in"
    grep '()' ../$x | sed 's|^[[:space:]]*||' | grep -v '^#'
done
